<?php

$council_members = array(
  1 => array(
    'name' => 'Margaret Chin',
    'email' => 'chin@council.nyc.gov',
  ),
  2 => array(
    'name' => 'Rosie Mendez',
    'email' => 'rmendez@council.nyc.gov',
  ),
  3 => array(
    'name' => 'Christine Quinn',
    'email' => 'cquinn@council.nyc.gov',
  ),
  4 => array(
    'name' => 'Daniel Garodnick',
    'email' => 'garodnick@council.nyc.ny.us',
  ),
  5 => array(
    'name' => 'Jessica Lappin',
    'email' => 'lappin@council.nyc.gov',
  ),
  6 => array(
    'name' => 'Gale Brewer',
    'email' => 'gbrewer@council.nyc.gov',
  ),
  7 => array(
    'name' => 'Robert Jackson',
    'email' => 'rjackson@council.nyc.gov',
  ),
  8 => array(
    'name' => 'Melissa Mark-Viverito',
    'email' => 'mviverito@council.nyc.gov',
  ),
  9 => array(
    'name' => 'Inez Dickens',
    'email' => 'idickens@council.nyc.gov',
  ),
  10 => array(
    'name' => 'Ydanis Rodriguez',
    'email' => 'yrodriguez@council.nyc.gov',
  ),
  11 => array(
    'name' => 'G. Oliver Koppell',
    'email' => 'okoppell@council.nyc.gov',
  ),
  12 => array(
    'name' => 'Larry Seabrook',
    'email' => 'seabrook@council.nyc.ny.us',
  ),
  13 => array(
    'name' => 'James Vacca',
    'email' => 'vacca@council.nyc.ny.us',
  ),
  14 => array(
    'name' => 'Fernando Cabrera',
    'email' => 'fcabrera@council.nyc.gov',
  ),
  15 => array(
    'name' => 'Joel Rivera',
    'email' => 'rivera@council.nyc.ny.us',
  ),
  16 => array(
    'name' => 'Helen Foster',
    'email' => 'foster@council.nyc.ny.us',
  ),
  17 => array(
    'name' => 'Maria del Carmen  Arroyo',
    'email' => 'marroyo@council.nyc.gov',
  ),
  18 => array(
    'name' => 'Annabel Palma',
    'email' => 'palma@council.nyc.ny.us',
  ),
  19 => array(
    'name' => 'Dan Halloran',
    'email' => 'dhalloran@council.nyc.gov',
  ),
  20 => array(
    'name' => 'Peter Koo',
    'email' => 'pkoo@council.nyc.gov',
  ),
  21 => array(
    'name' => 'Julissa Ferreras',
    'email' => 'jferreras@council.nyc.gov',
  ),
  22 => array(
    'name' => 'Peter F. Vallone, Jr.',
    'email' => 'vallone@council.nyc.ny.us',
  ),
  23 => array(
    'name' => 'Mark Weprin',
    'email' => 'mweprin@council.nyc.gov',
  ),
  24 => array(
    'name' => 'James Gennaro',
    'email' => 'jgennaro@council.nyc.gov',
  ),
  25 => array(
    'name' => 'Daniel Dromm',
    'email' => 'ddromm@council.nyc.gov',
  ),
  26 => array(
    'name' => 'James Van Bramer',
    'email' => 'jvanbramer@council.nyc.gov',
  ),
  27 => array(
    'name' => 'Leroy Comrie',
    'email' => 'comrie@council.nyc.ny.us',
  ),
  28 => array(
    'name' => 'Ruben Willis',
    'email' => 'Ruben.Wills@council.nyc.gov',
  ),
  29 => array(
    'name' => 'Karen Koslowitz',
    'email' => 'kkoslowitz@council.nyc.gov',
  ),
  30 => array(
    'name' => 'Elizabeth Crowley',
    'email' => 'ecrowley@council.nyc.gov',
  ),
  31 => array(
    'name' => 'James Sanders',
    'email' => 'jsanders@council.nyc.gov',
  ),
  32 => array(
    'name' => 'Eric Ulrich',
    'email' => 'eulrich@council.nyc.gov',
  ),
  33 => array(
    'name' => 'Stephen Levin',
    'email' => 'slevin@council.nyc.gov',
  ),
  34 => array(
    'name' => 'Diana Reyna',
    'email' => 'bbaruch@council.nyc.gov',
  ),
  35 => array(
    'name' => 'Letitia James',
    'email' => 'ljames@council.nyc.gov',
  ),
  36 => array(
    'name' => 'Albert Vann',
    'email' => 'avann@council.nyc.gov',
  ),
  37 => array(
    'name' => 'Erik Martin  Dilan',
    'email' => 'emdilan@council.nyc.ny.us',
  ),
  38 => array(
    'name' => 'Sara M. Gonzalez',
    'email' => 'gonzalez@council.nyc.ny.us',
  ),
  39 => array(
    'name' => 'Bradford S. Lander',
    'email' => 'lander@council.nyc.gov',
  ),
  40 => array(
    'name' => 'Mathieu Eugene',
    'email' => 'mathieu.eugene@council.nyc.gov',
  ),
  41 => array(
    'name' => 'Darlene Mealy',
    'email' => 'darlene.mealy@council.nyc.gov',
  ),
  42 => array(
    'name' => 'Charles Barron',
    'email' => 'cbarron@council.nyc.gov',
  ),
  43 => array(
    'name' => 'Vincent J. Gentile',
    'email' => 'vgentile@council.nyc.gov',
  ),
  44 => array(
    'name' => 'David Greenfield',
    'email' => 'dgreenfield@council.nyc.gov',
  ),
  45 => array(
    'name' => 'Jumaane D. Williams',
    'email' => 'jwilliams@council.nyc.gov',
  ),
  46 => array(
    'name' => 'Lewis Fidler',
    'email' => 'LFidler@council.nyc.gov',
  ),
  47 => array(
    'name' => 'Domenic M. Recchia, Jr.',
    'email' => 'recchia@council.nyc.ny.us',
  ),
  48 => array(
    'name' => 'Michael Chaim Nelson',
    'email' => 'nelson@council.nyc.ny.us',
  ),
  49 => array(
    'name' => 'Deborah Rose',
    'email' => 'drose@council.nyc.gov',
  ),
  50 => array(
    'name' => 'James Oddo',
    'email' => 'joddo@council.nyc.gov',
  ),
  51 => array(
    'name' => 'Vincent Ignizio',
    'email' => 'Ignizio@council.nyc.ny.us',
  ),
);

?>